
apiVersion: v1
kind: Service
metadata:
  name: qts-worker-sync-order-binance-service  
  namespace: default
spec:
  selector:
    app: qts-worker-sync-order-binance-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP